name: Deploy to Lambda
on: [push]
jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm test
        env:
          HONEYBADGER_API_KEY: ${{ secrets.HONEYBADGER_API_KEY }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      - name: Build binary
        run: |
          sh build.sh
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
          zip_file: function.zip
      - name: Report Honeybadger deployment
        uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.HONEYBADGER_API_KEY }}